name: 'releasebot'
description: 'Releasebot is a GitHub Action that automatically creates a release.'
author: 'Matt Biggs'

branding:
  icon: 'heart'
  color: 'red'

inputs:
  token:
    description: 'Your github token'
    required: true

runs:
  using: node20
  main: dist/index.js
