name: 'krytenbot'
description: 'Krytenbot is a GitHub Action that automatically creates a release.'
author: 'Matt Biggs'

branding:
  icon: 'heart'
  color: 'red'

inputs:
  token:
    description: 'Your github token'
    required: true
  milliseconds:
    description: 'Your input description here'
    required: true
    default: '1000'

outputs:
  time:
    description: 'Your output description here'

runs:
  using: node20
  main: dist/index.js
